### ISSUE TITLE
Improve tracking

### ISSUE THREAD

**Issue by roosi-ann** [concise-ee/superagile_app#131]
Esimesena teha ära lihtsamad asjad, et 30daks oleks olemas.
Asjad, mida oleks vaja mixpanelisse vm kohta kokku koguda, et neid oleks mugav vaadata:
Millistes kohtades loobutakse? Kui kaua mängus ollakse?
Milliste küsimuste kokkulepitud punktid on kõige madalamad/kõrgemad?
Kus on kõige rohkem eriarvamusi? (äkki on segaselt sõnastatud). Panna continue nupule logging juurde (kui peab uuesti hääletama)
Mis küsimusele kõige rohkem aega kulub? Keskmine aeg alates küsimuse ettetulekust kuni kokkulepitud skoorini

**Comment by TheAngryDuck** [comment]
Some of the tracking ideas were moved to the dashboard task.
